### ISSUE TITLE
你好，请问这边是参考了donglee-afar里面的logdeep吗？

### ISSUE THREAD

**Issue by zanedun** [ChuXin30/paper2#1]

**Comment by ChuXin30** [comment]
是的，还有[DeepLog-master]是参考wuyifan的

**Comment by zanedun** [comment]
谢谢回答，我这边正在做LogAnomaly的代码测试，我发现你在这个模块里面测试了许多模型（.pth结尾的文件）,似乎是成功了。我这边也想跑一哈自己的数据，再使用Drain解析了BGL数据集之后得到了bgl2_100k_structured.csv、bgl2_100k_templates.csv、BGL_sequence.csv。这之后我怎么能像他一样得到hdfs_train(我这里应该是bgl_train)。另外donglee在他的issue3给的模板向量化的程序你能成功运行吗？

**Comment by ChuXin30** [comment]
你要自己预处理，把bgl2_100k_structured.csv转换成相应的格式，简单来说就是把bgl2_100k_structured.csv按照滑动窗口划分，得到bgl_train，你可以参考一下BGL文件夹的data_processs.py里面有处理的代码。然后模板向量化我是也可以运行，不过我是自己提取的模板。

**Comment by zanedun** [comment]
好的，谢谢！

**Comment by zanedun** [comment]
不好意思，我还想问一哈，在data_processs.py中我最后输出了一个event_vector_top3.txt，请问这个就是模块向量化的结果吗？

**Comment by ChuXin30** [comment]
是的，不过这个是我自己写的，和log anomaly的论文不一样。

**Comment by zanedun** [comment]
好，谢谢。不一样也没事哈，我后面会改模板向量化这个模块！

**Comment by zanedun** [comment]
你好，我还想咨询一哈，你在demo下的loganomaly测试的模型我看F1-measure都是大于90%，这是针对HDFS的数据集还是针对BGL的数据集呢？我这边用LogAnomaly跑了一下loghub提供的BGL数据集，但是用训练出来的各模型来预测最终的F1-measure基本上都只有42%左右，当然这有可能是我用的数据量不够以及模型参数不合理，所以我想先向你那边求证一哈LogAnomaly跑BGL数据集的效果。

**Comment by ChuXin30** [comment]
应该是数据量用的不够多，或者使用随机划分的BGL数据集训练，我是使用随机20%bgl数据集训练，可以达到90%以上。

**Comment by zanedun** [comment]
好的，我去试一试！

**Comment by Hourenfeng** [comment]
> 你好，我还想咨询一哈，你在demo下的loganomaly测试的模型我看F1-measure都是大于90%，这是针对HDFS的数据集还是针对BGL的数据集呢？我这边用LogAnomaly跑了一下loghub提供的BGL数据集，但是用训练出来的各模型来预测最终的F1-measure基本上都只有42%左右，当然这有可能是我用的数据量不够以及模型参数不合理，所以我想先向你那边求证一哈LogAnomaly跑BGL数据集的效果。

您好，我目前刚开始学习这个领域，我想咨询一下您，如何使用demo下面的loganomaly跑BGL数据集呀，能指导一下我吗？
